### ISSUE TITLE
Ability to build squads from a raw text file

### ISSUE THREAD

**Issue by danbuis** [danbuis/ArmadaAIEngineNew#10]
Should have things like squad name, speed, hull, keywords

**Comment by danbuis** [comment]
Likely needed fields
SquadName
Unique
SquadType
Hull
Speed
AntiShipDice
AntiSquadronDice
Keywords
Points

**Comment by danbuis** [comment]
SquadName|Anakin Skywalker
Unique|Y
SquadType:BTL-B Y-wing
Hull|6
Speed|3
AntiShipDice|RB
AntiSquadronDice|BBB
Keywords|Bomber Heavy Adept2
Points|19
DefenseTokens|Br Br

SquadName|BTL-B Y-wing
Unique|N
SquadType|BTL-B Y-wing
Hull|6
Speed|3
AntiShipDice|K
AntiSquadronDice|BK
Keywords|Bomber Heavy
Points|10
DefenseTokens|

**Comment by danbuis** [comment]
For now I'm going to go ahead and limit it to the "wave 1" squads of all 4 factions.  That is more than enough to tide us over for a while.

**Comment by danbuis** [comment]
@Sobonis01 how does the above sound?

**Comment by Sobonis01** [comment]
Looks good, I can start working on those.

**Comment by danbuis** [comment]
Ill take care of it.  I think you are still neck deep in ships as text files

**Comment by danbuis** [comment]
Resolved in #24
