### ISSUE TITLE
Bring over some vassal graphics

### ISSUE THREAD

**Issue by danbuis** [danbuis/ArmadaAIEngineNew#22]
For now what i'm worried about are the ship models (not the bases), squadron models (not the bases) and the maps.

**Comment by danbuis** [comment]
Right now just porting over the above items and making sure they just have the models, which will be drawn over our BBDGeometry stuff to depict the miniature.

**Comment by Sobonis01** [comment]
How were the models in vassal made in the 1st place? BBDGeometry is the engine we are using to make the graphics?

**Comment by danbuis** [comment]
In vassal... Idk, it was secret sauce under the hood.  Vassal removes that level of detail from the users in order to lower the barrier to entry for making new modules.

To make new widgets you make a new component and toss a few inage filds, then you give it a few rules about when to render what.

We will be using the bbdgames library.  (Buis brothers dev)  it connects with the gpu to allow you to render.  It also can do 2d and 3d, so if we feel so inclined its a small leap comparably if we want to do 3d models, its really just seapping out a single image file for a 3d mesh.

It also has tooling specifically for geometry based operations, which I have not been able to find one I like.
