### ISSUE TITLE
Find out how to account for non standard arcs

### ISSUE THREAD

**Issue by Sobonis01** [danbuis/ArmadaAIEngineNew#31]
Issue: the way in which offsets are calculated will not work for the munificent and the SSD Aux Arc
What needs to be done: A way must be found in order to make an accurate arc calculation for non standard arcs.
Todo. 
1. upload photos of both units in order to help show the issue 
2. review ways in which to address this issue.  

Recommendation on course of action: lets work on steps listed, this needs to be completed prior to the AI being finished however it is not a top priority atm. As 3 of the other 4 factions may be used. 

TBX: Complete step todo 1 by eod Thursday January 14th

**Comment by danbuis** [comment]
You uh, missed your TBX... assuming it was Jan 14 2021
