### ISSUE TITLE
Rename window for when the game launches

### ISSUE THREAD

**Issue by danbuis** [danbuis/ArmadaAIEngineNew#45]
## Requirements
Right now the window for the program is just called "GAME".  We need something better

## Potential Solutions
Put something better in the string that assigns the window title

## Potential Tasks
What does it take to call this issue complete?

  - [x] DefDone: Something better shows up when running the app

**Comment by danbuis** [comment]
@Sobonis01 I'm assigning this one to you because its small, fairly straightforward, and will force you to explore the OpenGL side of the code, rather than the objects, parsers etc that you have been doing.

This one has no blockers and can be done at anytime.  It should require you to change 1 line.

**Comment by Sobonis01** [comment]
I will look up opengl and get some ideas.

**Comment by danbuis** [comment]
Just to reiterate... The change is,in this repo, and doesn't require you to know all the ins and puts of opengl.  Just track down where the window title gets set.

**Comment by Sobonis01** [comment]
Is this the line of code you want to me to change 

import BBDGameLibrary.GameEngine.Engine;
import BBDGameLibrary.GameEngine.GameComponent;
import engine.ArmadaGame;

public class ArmadaAIMain {

	public static void main(String[] args) {
		try {
			GameComponent gameLogic = new ArmadaGame();
			Engine gameEng = new Engine("GAME",  
					1800, 980, true, gameLogic);
			gameEng.run();
		} catch (Exception excp) {
			excp.printStackTrace();
			System.exit(-1);
		}
	}

}
Should i replace the word GAME with Star Wars Aramda AI
