### ISSUE TITLE
Create a way to create ships from the text file 

### ISSUE THREAD

**Issue by Sobonis01** [danbuis/ArmadaAIEngineNew#59]
## Requirements
We create a way to read the ships.txt file and put them into the game

## Potential Solutions
change the squad file to work for the ship field by changing lines of code 
maybe make a ships.txt file for a one ship do not include stuff like the upgrades.  
to test it. 
## Potential Tasks
Make sure the that everything will run 
load files from ships.txt
create ships.  
work on how to do upgrades.

**Comment by Sobonis01** [comment]
This is a work in process let me know what you think 

[The Shipyard.txt](https://github.com/danbuis/ArmadaAIEngineNew/files/6253077/The.Shipyard.txt)

**Comment by danbuis** [comment]
Out of curiosity what program did you use to make that file?

**Comment by danbuis** [comment]
At a glance it looks ok.  I see a few things that look iffy, but those should work themselves out as you test and compile etc.

**Comment by Sobonis01** [comment]
[Ship factory.txt](https://github.com/danbuis/ArmadaAIEngineNew/files/6448562/Ship.factory.txt)

**Comment by boredompwndu** [comment]
What is the purpose of this file? I am confused

**Comment by danbuis** [comment]
Just a couple of notes @Sobonis01 

1)  Instead of attaching a file for us, go ahead and get a pull request started and push changes to that.  That's cleaner than files for us to download and view.
2) You likely want a java class file, not a text file, especially since the text in the file is formatted like a java file.

**Comment by danbuis** [comment]
Happy to help with any of that tomorrow

**Comment by danbuis** [comment]
Closeing as this is a repeat of #6
