### ISSUE TITLE
Build a basic ship template

### ISSUE THREAD

**Issue by danbuis** [danbuis/ArmadaAIEngineNew#6]
Basically at this point we will have a BasicShip class that takes in a ship name as a constructor, and then it grabs the correct data from the file from #3 and builds out a ship.

Checklist (non exhaustive, I probably missed something)
- [x] Create a new branch based off of `Raw-Text`
- [x] Create a basic class file for the ships, defining what variables you think it needs, and an empty default constructor
- [x] Commit to your branch, publish, and open a pull request so that your code is out in the world.
- [x] Add a fancier constructor so you can build a ship by passing in all its parameters/values.
- [x] Create a bare bones class file to parse your ship file.  Probably should model it on the squadron parser for consistancy.
- [x] Write a function to parse the ship file and make your ship objects from earlier.  Should probably model this on the squadron parser constructor at https://github.com/danbuis/ArmadaAIEngineNew/pull/26/commits/b4e05569abfaa15d94976999c5e8d241eced00ae for simplicity.
- [x] Write a unit test to make sure that what you have right now works right.  If it does, great, let's refine it.
- [x] Start creating some "bad" ship text files in the test assets folder like the squadron ones.  For each line that needs to be something specific for consistancy or other reasons do a file and a unit test to make sure that you catch bad file structures.  use the parsing utils class to perform validations
- [x] Assuming all unit tests pass, I'd say this one is ready for review now.

**Comment by danbuis** [comment]
The goal is to make ship objects, similar to how earlier we made squad objects.  We will cover rendering in another issue, that way you don't need to think about integrating with the BBDGamesLibrary yet.  (And that gives me time to get the next release wrapped up)

**Comment by Sobonis01** [comment]
package gameComponents;

import java.lang.reflect.Array;
import java.util.ArrayList;

public class Ships small {


    private final String size;
    private final String name;
    private final boolean unique;
    private final int fullhealth;
    private final int Speed;
    private final String FrontArc;
    private final String SideArc;
    private final String RearArc;
    private final String AntiSquadron;
    private final ArrayList<String> keywords;
    private final int pointsValue;
    private ArrayList<String> Upgrade
    private ArrayList<String> defenseTokens;

    public Ship(String type, String name, boolean unique, int fullHealth,
                    int maxSpeed, String FrontArc, String SideArc, String RearArc String, AntiSquadron,
                    ArrayList<String> keywords, int pointsValue, ArrayList<String> defenseTokens){
        this.type = type;
        this.name = name;
        this.fullHealth = fullHealth;
        this.currentHealth = fullHealth;
        this.fullshield
        this.maxSpeed = maxSpeed;
        this.SideArc= SideArc;
        this.RearArc = RearArc;
        this.FrontArc = FrontArc;
        this.AntiSquadron = antiSquadron;
        this.keywords = keywords;
        this.pointsValue = pointsValue;
        this.Upgrade = Upgrade;
        this.defenseTokens = defenseTokens;

Here is the problem I am running into I am trying to find out the best way to account for shields. 

I put the shields as 

FrontArc 4 |RRRBBKKK
SideArc 3 |RBKK
RearArc 2 |RBK

maybe try 
private final Int RearArc
That way it pulls the Int or the number inside of the dice?  or should I have written the ship file as 
FrontArc| 4 |RRRBBKKK
SideArc| 3 |RBKK
RearArc| 2 |RBK
would that work better?

**Comment by danbuis** [comment]
Good question.

I'll start off by stating that our parser **requires** each line to be formatted key - delimeter - value.  In our case that is in the format `FrontArc 4 |RRRBBKKK`

Since we are trying to include 2 pieces of related information in one line that won't work... kinda.

With the above format it is implied that every ship has a `FrontArc 4` key, which won't be true, since that 4 changes for every ship.

We have 2 possible solutions I can think of right away.
1) We can change to something like
`FrontShields|4
FrontArmament|RRRBBKKK`

This has the advantage of being readable quickly early on in the text file, but has the disadvantage of creating more data points to handle.

2) We can change to something like 
`FrontHullZone|4RRRBBKKK`

This has the advantage of putting all related data in one line/package.
We will have to be making a HullZone class anyway pretty much right after this one, simply because hull zones have so much logic like shields, dice, line of sight etc.  We can pass the string to the hull zone and let it handle parsing it by grabbing the first character for one thing and all the rest for something else.

**Comment by danbuis** [comment]
Also, don't forget to open up a new pull request.  That makes it easier for code related dicussions to happen because you don't need to copy/paste files or code chunks, and it makes it easier for me to see the overall picture of your current code base.

**Comment by Sobonis01** [comment]
This might be overthinking it, but if we did Boolean for each upgrade, ie Turbo 
boolean Turbolaser = true;
private ArrayList<String> Turbolaser upgrade
//This it to confirm if the ship can use a Turbolaser// 
Private class Main {
  Private static void main(String[ ] args) {
    ArrayList<String> Turbolaser = new ArrayList<String>( );
    Turbolaser.add("LTT");
    Turbolaser.add("XI7");
    Turbolaser.add("H9");
    
    Random rand; // Global variable

Private static String  randomItem(Arraylist<String> mylist) {
    rand = new Random(); 
    String randomString = lista.get(rand.nextString(lista.size()));
    return randomString;
I might have frankenstein code up here to make it pick random Turbo laser.  
I need to think of a way to make it limit to one Turbolaser. Then further down the line make it chose the smart turbolaser, or illegal combo, like 2 mods.

**Comment by danbuis** [comment]
Let's worry about list building things later.  If you want to open a discussion on that, feel free to open a dedicated issue.

With the caveat that the following discussion probably belongs in an issue dedicated to upgrades, so if you want to talk more, copy things over there...
I'm not opposed to a list of booleans.  Do you have an idea for how to handle ships with dual upgrade slots?  ie Quasar, or the Liberty etc.  I had been planning to keep a list of slots and then throw upgrades at that list of slots to see if it was valid, but since nothing has been written I'm willing to discuss ideas on implementation.

Either way, for this issue here and how, importing a list of Strings is fine for now until we start getting something like a proper upgrade object plan thing.  Once that settles we will revisit the Ship parser and make something more appropriate from the input file.
