### ISSUE TITLE
Centralize simple enums

### ISSUE THREAD

**Issue by danbuis** [danbuis/ArmadaAIEngineNew#65]
## Requirements
We are going to soon have at least 4 basic enums floating in a few places.  They need to be centralized

## Potential Solutions
~~Make an enums class similar to the GameConstants file where we can put all our enums that don't have attached logic.~~
Put enums as static objects inside the appropriate classes (ex: Defense token enums exist in the defense token class)

## Potential Tasks
What does it take to call this issue complete?

  - [ ] Pass all unit tests
  - [ ] All Enums without extra logic live together in one place.

**Comment by boredompwndu** [comment]
~~edit: Put enums as static objects~~

Edit I am the big dumb and can't read the close button isn't a cancel button

**Comment by danbuis** [comment]
There are 2 in the attack pool PR that still needs to be merged, and 2 from def tokens

**Comment by danbuis** [comment]
GameConstants.CURRENT_FACTIONS

Found this guy....

**Comment by boredompwndu** [comment]
> GameConstants.CURRENT_FACTIONS
> 
> Found this guy....

Where should this go? I feel like there are a lot of places where faction comes up. It should be simpleEnum'ified at minimum though

**Comment by danbuis** [comment]
Its used in the parsing validator thing, so maybe there as an anonymous inner enum or whatever?
